### ISSUE TITLE
Set edition within the frontmatter

### ISSUE THREAD

**Issue by epage** [avsaase/cargo-new-script#4]
`cargo new` always sets the edition to "current" to avoid getting the 2015 edition. With cargo scripts, the default is "current" but it warns and if something is being scaffolded it should probably include that level of "boilerplate" to remove the warning and make the script work across Rust versions

**Comment by avsaase** [comment]
https://github.com/avsaase/cargo-new-script/pull/2 added passing the `--quiet` flag to cargo by default which also suppresses the warning. I'll add the edition specifier for completeness. Thanks for the suggestion.

**Comment by epage** [comment]
imo `--quiet` is a short-term hack until we have native support for quieter cargo output.  My plan is to show build progress but then to clear it away at the end.  Warnings will likely be left shown though.

**Comment by epage** [comment]
Also, to put this a different way, if cargo were to add "new script" support, it would be setting the Edition.

**Comment by avsaase** [comment]
> imo `--quiet` is a short-term hack until we have native support for quieter cargo output. My plan is to show build progress but then to clear it away at the end. Warnings will likely be left shown though.

That would be great. With `--quiet` you don't get any feedback on what going on while compiling and your script seems to hang. 

> Also, to put this a different way, if cargo were to add "new script" support, it would be setting the Edition.

Makes sense. It's a bit boilerplate-y to specify the edition but it's better than breaking old scripts.

**Comment by avsaase** [comment]
Added in https://github.com/avsaase/cargo-new-script/commit/80145e194578f4bea40afba9e30a9865eae4a85d.
